# @package _global_
cwd_path: "."   # gets expanded to an absolute path to the original current directory (not the Hydra/runtime working dir)
cuda_idx: 0     # set to None to run without using CUDA

general:
  vocab_words: ${cwd_path}/conf/vocab.txt
  discount_gamma: 0.5
  random_seed: 42
  use_cuda: True  # disable this when running on machine without cuda

  # replay memory
  replay_memory_capacity: 500000  # adjust this depending on your RAM size
  replay_memory_priority_fraction: 0.25
  update_per_k_game_steps: 4
  replay_batch_size: 32

  # epsilon greedy
  epsilon_anneal_episodes: 300  # -1 if not annealing
  epsilon_anneal_from: 1.0
  epsilon_anneal_to: 0.2

checkpoint:
  experiment_tag: 'gvs-symbolic-baseline'
  model_checkpoint_path: 'saved_models'
  load_pretrained: False  #True  # during test, enable this so that the agent loads your pretrained model
  pretrained_experiment_tag: 'gvs-symbolic-baseline_episode_5400'  #'gvs-symbolic-baseline_episode_12300'
  save_frequency: 100

training:
  games:   # a list of game files or directories containing game files
  - ~/work/0_magd3/CodaLab/cogEx1
  batch_size: 2   # 16
  sync_rate: 100   # 1000  # how often to swap in the target network
  nb_epochs: 1
  max_episode_steps: 50  # after this many steps, a game is terminated
  optimizer:
    step_rule: 'adam'  # adam
    learning_rate: 0.001
    clip_grad_norm: 5

test:
  games:   # a list of game files or directories containing game files
  -  ~/work/0_magd3/cog2019_ftwp/games/valid
  batch_size: 2   # 16
  #limit_test_batches: 5  #speed up debugging cycle by only evaluating a subset of test set
  num_test_episodes: 10

model:
  embedding_size: 64
  encoder_rnn_hidden_size: [192]
  action_scorer_hidden_dim: 128
  dropout_between_rnn_layers: 0.
